config/routes.rb
SampleApp::Application.routes.draw do
  resources :rewards

  resources :accounts

  resources :reports

  resources :products

  resources :resellers

  resources :invitations

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/tour',    :to => 'pages#tour'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/claimform', :to => 'rewards#claimform'
  match 'treasurehunt', :to => 'rewards#treasurehunt'
  
  root :to => 'pages#home'

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  PRODUCT_CATEGORY = ["Routers", "Switches", "Wireless", "Security"]
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  # GET /rewards
  # GET /rewards.xml
  
  layout :cp_layout
  
  def claimform
    	@title = "Claim Form"
    	@user = current_user
      @title = @user.name
  end
  
  def treasurehunt
    	@title = "Treasure Hunt"
    	@user = current_user
      @title = @user.name
  end
  
  def index
    @rewards = Reward.all
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rewards }
    end
  end

  # GET /rewards/1
  # GET /rewards/1.xml
  def show
    @reward = Reward.find(params[:id])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reward }
    end
  end

  # GET /rewards/new
  # GET /rewards/new.xml
  def new
    @reward = Reward.new
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reward }
    end
  end

  # GET /rewards/1/edit
  def edit
    @reward = Reward.find(params[:id])
    @user = current_user
    @title = @user.name
  end

  # POST /rewards
  # POST /rewards.xml
  def create
    @reward = Reward.new(params[:reward])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      if @reward.save
        format.html { redirect_to(@reward, :notice => 'Reward was successfully created.') }
        format.xml  { render :xml => @reward, :status => :created, :location => @reward }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rewards/1
  # PUT /rewards/1.xml
  def update
    @reward = Reward.find(params[:id])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      if @reward.update_attributes(params[:reward])
        format.html { redirect_to(@reward, :notice => 'Reward was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reward.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.xml
  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html { redirect_to(rewards_url) }
      format.xml  { head :ok }
    end
  end
  
  def cp_layout
    if signed_in?
      "cp"
    else
      "application"
    end
  end
  
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(@reward) do |f| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% @reward.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rewards/claimform.html.erb
<div class="contentcontainer">
   <div class="headings altheading">
       <h2>Sales Claims</h2>
   </div>
   <div class="contentbox">

<ol>
	<li>If the product you are looking for is not on the list, please email support@example.com</li>
	<li>Claims will be approved by the 25th of the month following the claim period and points will then be available for you to spend.</li>
	</li>Claims must be made within 5 days of the end of the month in which the sale was made, so make sure you log your sales in plenty of time for them to be verified.</li>
</ol>
	<br />
	<br />
	<h3>Enter new sales claim here:</h3>
	<table>
		<thead>
			<tr>
				<th>Product Category</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>P/O Number</th>
				<th>Sale Value</th>
				<th>Date of Sale</th>
				<th></th>
			</th>
		</thead>
		<tbody>
			<tr>
				<td>
					<select>
						<option>Router</option>
						<option>Switch</option>
						<option>Wireless</option>
					</select>
				</td>
				<td>
					<select>
						<option>Cisco 3900</option>
						<option>Cisco 2900</option>
						<option>Cisco 1900</option>
					</select>
				</td>
				<td>
					<input type="text" size="7">
				</td>
				<td>
					<input type="text" size="12">
				</td>
				<td>
					<input type="text" size="12">
				</td>
				<td>
					<input type="text" size="12">
				</td>
				<td>
					<button type="button">Add</button>
				</td>	
			</tr>
		</tbody>
		</table>
		<br />
		<br />
		<h3>Your previously logged sales claims:</h3>
		<table>
			<thead>
				<tr>
					<th>Date Logged</th>
					<th>Product</th>
					<th>Quantity</th>
					<th>P/O Number</th>
					<th>Sale Value</th>
					<th>Date of Sale</th>
					<th>Points</th>
					<th>Status</th>
					<th></th>
					<th></th>
					<th></th>
				</th>
			</thead>
		

app/views/rewards/edit.html.erb
<h1>Editing reward</h1>

<%= render 'form' %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<!-- Alternative Content Box Start -->
    <div class="contentcontainer">
       <div class="headings altheading">
           <h2>Rewards Catalog</h2>
       </div>
       <div class="contentbox">
       	<table width="100%">
           	<thead>
               	<tr>
                   	   <th>Reward</th>
                       <th></th>
					   <th>Description</th>
					   <th>Points</th>
					   <th><th>
					   <th></th>
                       
					   
                   </tr>
               </thead>
               <tbody>
						
					<% @rewards.each do |reward| %>
               	<tr>
                   	    <td><%= image_tag(reward.image_url) %></td>
						<td><%= reward.title %></td>
                        <td><%= reward.description %></td>
					    <td><%= reward.points %></td>
					   
                       
                       
                   </tr>
					<% end %>
					
                   
                   
                    
               </tbody>
           </table>
           <!-- <div class="extrabottom">
           	<ul>
				<li><%= image_tag("cp/icons/icon_approve.png") %> Show</li>
               	<li><%= image_tag("cp/icons/icon_edit.png") %> Edit</li>
                <li><%= image_tag("cp/icons/icon_delete.png") %> Remove</li>
               </ul>
           </div>-->
       </div>
   </div>
  <!-- Alternative Content Box End -->


<!-- <%= link_to 'New Product', new_product_path %> -->

app/views/rewards/new.html.erb
<h1>New reward</h1>

<%= render 'form' %>

<%= link_to 'Back', rewards_path %>

app/views/rewards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @reward.title %>
</p>

<p>
  <b>Description:</b>
  <%= @reward.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @reward.image_url %>
</p>

<p>
  <b>Points:</b>
  <%= @reward.points %>
</p>


<%= link_to 'Edit', edit_reward_path(@reward) %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/treasurehunt.html.erb
<div class="contentcontainer">
   <div class="headings altheading">
       <h2>Welcome, to the Cisco Treasure Hunt.</h2>
   </div>
   <div class="contentbox">

	<p>For the next eight weeks we are giving you the chance to win an amazing holiday for two around the Mediterranean. We have dropped a number of treasure chests at our reseller locations around Europe and for every 100 points you collect you will receive a clue which will lead you to a resellers location and its treasure chest. Inside each chest is the clue to the next reseller location. Solve the clue, collect your next 100 hundred points and move one step closer to the finish.
	</p>
	<p>We will also be giving you the chance to collect extra points over the next eight weeks to help you reach the next treasure chest a little faster. Keep an eye out for selected products which carry bonus points. Also a lucky few treasure chests contain spot prizes so get collecting and start hunting!</p>
	<p>Best of luck</p>
	<br />
	<br />
	<h3>How it works:</h3>
	<table width="50%">
		
		<tbody>
			<tr>
				<td>
					<%= image_tag("cp/webex.gif") %>
				</td>
				<td>
					Every Cisco product has a point value, collect 100 points to receive your first clue. Throughout the competition you will also have the chance to pick up bonus points which will be available on selected Cisco products so be sure to check in regularly for updates. 
				</td>
			</tr>
			<tr>
				<td>
					<%= image_tag("cp/google_map_xsmall1.jpg") %>
				</td>
				<td>
					With every 100 points collected you will receive a clue which, when solved, leads to the location of one of our resellers. If you think you have solved your clue head to that location on our Google map to see if you are correct. If you're at the right location you will see another clue which along with your next 100 points will lead you further along the map towards the final treasure chest.
				</td>
			</tr>
			<tr>
				<td>
					<%= image_tag("cp/treasure_chest.jpg") %>
				</td>
				<td>
					At random reseller locations on the map certain treasure chests will contain spot prizes and bonus points. To help you along your journey we will also be offering bonus clues located within our reseller portal so be sure to log in regularly to stay up to date.
				</td>
			</tr>
			<tr>
				<td>
					<%= image_tag("cp/treasure_progress_ma.jpg") %>
				</td>
				<td>
					Wondering how close you are to the treasure? We will soon be launching a chart which will track every resellers journey along the map. Falling behind? Get selling! Sign up to our email bulletins which will keep you updated with everything thats happening in the treasure hunt during the previous week. And don't forget to log in regularly for the latest news and clues!
					</td> 
				</tr>
				<tr>
					<td>
						<%= image_tag("cp/open_treasure_chest.jpg") %>
					</td>
					<td>At the end of this epic journey one reseller will emerge triumphant winning an amazing Mediterranean cruise and the title of Top Reseller 2011! We will also have a number of runner up and spot prizes so there is really no reason not to enter.!
						</td> 
			</tr>
				
		</tbody>
		</table>
		