config/routes.rb
SampleApp::Application.routes.draw do
  resources :rewards

  resources :accounts

  resources :reports

  resources :products

  resources :resellers

  resources :invitations

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/tour',    :to => 'pages#tour'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/claimform', :to => 'rewards#claimform'
  match 'treasurehunt', :to => 'rewards#treasurehunt'
  
  root :to => 'pages#home'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  has_one :receipient, :class_name => 'User'
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.xml
  
  # layout :cp_layout

  # GET /invitations/new
  # GET /invitations/new.xml
  
  layout :cp_layout
  
  def new
    @invitation = Invitation.new
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # POST /invitations
  # POST /invitations.xml
  def create
    @invitation = Invitation.new(params[:invitation])
    @user = current_user
    @title = @user.name
    UserMailer.reseller_added(@invitation).deliver

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to(@invitation, :notice => 'Thank you, your invitation has been sent.') }
        format.xml  { render :xml => @invitation, :status => :created, :location => @invitation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invitation.errors, :status => :unprocessable_entity }
      end
    end
  end

 private

 def cp_layout
   if signed_in?
     "cp"
   else
     "application"
   end
 end
  
  #def cp_layout
   # if signed_in?
    #  "cp"
    #else
     # "application"
    #end
  #end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being sent:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :receipient_email, "Reseller's email address" %><br />
    <%= f.text_field :receipient_email %>
  </div>
  <div class="field">
    <%= f.label :property, "Territory"%><br />
    <%= f.text_field :property %>
  </div>
  
  <div class="actions">
    <%= f.submit "Send invite"%>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Sender</th>
    <th>Receipient email</th>
    <th>Property</th>
    <th>Token</th>
    <th>Sent at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.sender_id %></td>
    <td><%= invitation.receipient_email %></td>
    <td><%= invitation.property %></td>
    <td><%= invitation.token %></td>
    <td><%= invitation.sent_at %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Destroy', invitation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sender:</b>
  <%= @invitation.sender_id %>
</p>

<p>
  <b>Receipient email:</b>
  <%= @invitation.receipient_email %>
</p>

<p>
  <b>Property:</b>
  <%= @invitation.property %>
</p>

<p>
  <b>Token:</b>
  <%= @invitation.token %>
</p>

<p>
  <b>Sent at:</b>
  <%= @invitation.sent_at %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>