config/routes.rb
SampleApp::Application.routes.draw do
  resources :rewards

  resources :accounts

  resources :reports

  resources :products

  resources :resellers

  resources :invitations

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/tour',    :to => 'pages#tour'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/claimform', :to => 'rewards#claimform'
  match 'treasurehunt', :to => 'rewards#treasurehunt'
  
  root :to => 'pages#home'

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.xml
  
  layout :cp_layout
  
  def index
    @reports = Report.all
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    @report = Report.new
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
    @user = current_user
    @title = @user.name
  end

  # POST /reports
  # POST /reports.xml
  def create
    @report = Report.new(params[:report])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      if @report.save
        format.html { redirect_to(@report, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    @report = Report.find(params[:id])
    @user = current_user
    @title = @user.name

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to(@report, :notice => 'Report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    @user = current_user
    @title = @user.name

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end
  
  private

    def cp_layout
      if signed_in?
        "cp"
      else
        "application"
      end
    end
  
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<div class="contentcontainer">
        <div class="headings alt">
            <h2>Sales by Product</h2>
        </div>
        <div class="contentbox">
        	<table>
            	<tr>
                	<td width="150"><strong><span class="usagetxt redtxt">Product_1</span> usage bar:</strong></td>
                    <td width="500">
                    	<div class="usagebox">
            				<div class="highbar" style="width: 85%;"></div>
                        </div>
                    </td>
                </tr>
                <tr>
                	<td><strong><span class="usagetxt orangetxt">Product_2</span> usage bar:</strong></td>
                    <td>
                    	<div class="usagebox">
            				<div class="midbar" style="width: 50%;"></div>
                        </div>
                    </td>
                </tr>
                <tr>
                	<td><strong><span class="usagetxt greentxt">Product_3</span> usage bar:</strong></td>
                    <td>
                    	<div class="usagebox">
            				<div class="lowbar" style="width: 25%;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Graphs Box Start -->
<div class="contentcontainer" id="graphs">
    <div class="headings alt">
        <h2 class="left">Dynamic graph types</h2>
        <ul class="smltabs">
        	<li><a href="#graphs-1">Area chart</a></li>
            <li><a href="#graphs-2">Pie chart</a></li>
            <li><a href="#graphs-3">Line graph</a></li>
            <li><a href="#graphs-4">Bar graph</a></li>
        </ul>
    </div>
    <div class="contentbox" id="graphs-1">
			<table style="display: none;" class="area">
                <caption> Registered Members</caption>
                <thead>
                    <tr>
                        <td></td>
                        <th scope="col">Jan</th>
                        <th scope="col">Feb</th>
                        <th scope="col">March</th>
                        <th scope="col">April</th>
                        <th scope="col">May</th>
                        <th scope="col">June</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">2010</th>
                        <td>190</td>
                        <td>160</td>
                        <td>40</td>
                        <td>120</td>
                        <td>30</td>
                        <td>70</td>
                    </tr>
                    <tr>
                        <th scope="row">2009</th>
                        <td>3</td>
                        <td>40</td>
                        <td>30</td>
                        <td>45</td>
                        <td>35</td>
                        <td>49</td>
                    </tr>	
                </tbody>
            </table>
    </div>
    <div class="contentbox" id="graphs-2">
    	<table style="display: none;" class="pie">
            <caption> Registered Members</caption>
                <thead>
                    <tr>
                        <td></td>
                        <th scope="col">Jan</th>
                        <th scope="col">Feb</th>
                        <th scope="col">March</th>
                        <th scope="col">April</th>
                        <th scope="col">May</th>
                        <th scope="col">June</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">2010</th>
                        <td>190</td>
                        <td>160</td>
                        <td>40</td>
                        <td>120</td>
                        <td>30</td>
                        <td>70</td>
                    </tr>
                    <tr>
                        <th scope="row">2009</th>
                        <td>3</td>
                        <td>40</td>
                        <td>30</td>
                        <td>45</td>
                        <td>35</td>
                        <td>49</td>
                    </tr>	
                </tbody>
            </table>
    </div>
    <div class="contentbox" id="graphs-3">
			<table style="display: none;" class="line">
                <caption> Registered Members</caption>
                <thead>
                    <tr>
                        <td></td>
                        <th scope="col">Jan</th>
                        <th scope="col">Feb</th>
                        <th scope="col">March</th>
                        <th scope="col">April</th>
                        <th scope="col">May</th>
                        <th scope="col">June</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">2010</th>
                        <td>190</td>
                        <td>160</td>
                        <td>40</td>
                        <td>120</td>
                        <td>30</td>
                        <td>70</td>
                    </tr>
                    <tr>
                        <th scope="row">2009</th>
                        <td>3</td>
                        <td>40</td>
                        <td>30</td>
                        <td>45</td>
                        <td>35</td>
                        <td>49</td>
                    </tr>	
                </tbody>
            </table>
    </div>
    <div class="contentbox" id="graphs-4">
			<table style="display: none;" class="bar">
               <caption> Registered Members</caption>
                <thead>
                    <tr>
                        <td></td>
                        <th scope="col">Jan</th>
                        <th scope="col">Feb</th>
                        <th scope="col">March</th>
                        <th scope="col">April</th>
                        <th scope="col">May</th>
                        <th scope="col">June</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">2010</th>
                        <td>190</td>
                        <td>160</td>
                        <td>40</td>
                        <td>120</td>
                        <td>30</td>
                        <td>70</td>
                    </tr>
                    <tr>
                        <th scope="row">2009</th>
                        <td>3</td>
                        <td>40</td>
                        <td>30</td>
                        <td>45</td>
                        <td>35</td>
                        <td>49</td>
                    </tr>	
                </tbody>
            </table>
    </div>
</div>
<!-- Graphs Box End -->


 <div class="contentcontainer">
        <div class="headings alt">
            <h2>Usage bar exmaples</h2>
        </div>
        <div class="contentbox">
        	<table>
            	<tr>
                	<td width="150"><strong><span class="usagetxt redtxt">Red</span> usage bar:</strong></td>
                    <td width="500">
                    	<div class="usagebox">
            				<div class="highbar" style="width: 85%;"></div>
                        </div>
                    </td>
                </tr>
                <tr>
                	<td><strong><span class="usagetxt orangetxt">Orange</span> usage bar:</strong></td>
                    <td>
                    	<div class="usagebox">
            				<div class="midbar" style="width: 50%;"></div>
                        </div>
                    </td>
                </tr>
                <tr>
                	<td><strong><span class="usagetxt greentxt">Green</span> usage bar:</strong></td>
                    <td>
                    	<div class="usagebox">
            				<div class="lowbar" style="width: 25%;"></div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>


<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>